package io.snaps.corecommon.strings

enum class StringKey {

    ActionStart,
    ActionSave,
    ActionReply,
    ActionReload,
    ActionContinue,

    ErrorLoadFail,

    ConnectionSuccessMessage,
    ConnectionErrorMessage,
    UnknownErrorMessage,

    NumPadForget,

    RegistrationMessagePrivacyPolicy,
    RegistrationActionPrivacyPolicy,
    RegistrationActionTermsOfUse,
    RegistrationActionLoginWithEmail,
    RegistrationActionLoginWithGoogle,
    RegistrationActionLoginWithFacebook,
    RegistrationActionLoginWithTwitter,
    RegistrationTitle,
    RegistrationFieldOr,
    RegistrationDialogSignInTitle,
    RegistrationDialogSignInMessage,
    RegistrationDialogSignInHintEmail,
    RegistrationDialogSignInHintPassword,
    RegistrationDialogSignInActionLogin,
    RegistrationDialogSignInActionRegistration,
    RegistrationDialogSignUpTitle,
    RegistrationDialogSignUpMessage,
    RegistrationDialogSignUpHintEmail,
    RegistrationDialogSignUpHintPassword,
    RegistrationDialogSignUpHintConfirmPassword,
    RegistrationDialogSignUpActionLogin,
    RegistrationDialogSignUpActionRegistration,
    RegistrationDialogVerificationTitle,
    RegistrationDialogVerificationMessage,
    RegistrationDialogVerificationAction,

    SubsActionSubscriptions,
    SubsActionSubscribers,
    SubsActionFollow,
    SubsActionFollowing,

    CreateUserTitle,
    CreateUserMessage,
    CreateUserHintNickname,
    CreateUserFieldPhotoUploaded,
    CreateUserActionUploadPhoto,
    CreateUserActionStart,

    PhotoDialogTitle,
    PhotoDialogActionPickPhoto,
    PhotoDialogActionTakePhoto,
    PhotoDialogActionCancel,

    PopularVideosTitle,
    PopularVideosHint,

    WalletImportTitle,
    WalletImportMessageEnterPhrases,
    WalletImportHint,

    ConnectWalletTitle,
    ConnectWalletMessage,
    ConnectWalletActionCreate,
    ConnectWalletActionImport,

    CreateWalletTitle,
    CreateWalletMessage,
    CreateWalletAction,

    CreatedWalletTitle,
    CreatedWalletMessage,
    CreatedWalletAction,

    MnemonicsTitle,
    MnemonicsMessage,

    VerificationTitle,
    VerificationMessage,

    ReferralProgramTitle,
    ReferralProgramTitleEnterCode,
    ReferralProgramMessageEnterCode,
    ReferralProgramActionEnterCode,
    ReferralProgramHintCode,
    ReferralProgramHintLink,
    ReferralProgramTitleDirectReferral,
    ReferralProgramMessageDirectReferral,
    ReferralProgramActionInviteUser,
    ReferralProgramInviteDialogTitle,
    ReferralProgramInviteDialogMessage,
    ReferralProgramDialogActionClose,
    ReferralProgramCodeDialogTitle,
    ReferralProgramCodeDialogMessage,
    ReferralProgramCodeDialogActionInvite,
    ReferralProgramCodeDialogHintEnterCode,

    SettingsTitle,
    SettingsTitleWallet,
    SettingsTitleReferralProgram,
    SettingsTitleSocialNetworks,
    SettingsTitleAboutProject,
    SettingsActionLogout,
    SettingsActionDeleteAccount,

    SocialNetworksTitle,
    SocialNetworksTitleDiscord,
    SocialNetworksTitleTelegram,

    TasksTitleSlideCurrent,
    TasksTitleSlideHistory,
    TasksTitleCurrent,
    TasksTitleHistory,
    TasksTitleMessageCurrent,
    TasksTitleMessageHistory,
    TasksTitleRemainingTime,

    TaskWatchVideoTitle,
    TaskWatchVideoFieldJobCompleted,
    TaskLikeAndSubscribeTitle,

    TaskShareTitle,

    TaskFindPointsTitle,
    TaskFindPointsTitleConnectInstagram,
    TaskFindPointsTitlePointId,
    TaskFindPointsMessage,
    TaskFindPointsActionConnect,
    TaskFindPointsActionVerify,
    TaskFindPointsActionNotFound,
    TaskFindPointsTitleSponsor,

    WalletSettingsTitle,
    WalletSettingsTitleBackup,
    WalletSettingsDescriptionBackup,
    WalletSettingsBackupDialogTitle,
    WalletSettingsBackupDialogMessage,
    WalletSettingsBackupDialogAction,

    BackupWalletKeyTitle,
    BackupWalletKeyMessage,
    BackupWalletKeyActionHold,

    WalletTitle,
    WalletFieldTotal,
    WalletTitleTopUp,
    WalletTitleWithdraw,
    WalletTitleExchange,
    WalletTitleBalance,
    WalletTitleSelectCurrency,
    WalletMessageTopUp,
    WalletMessageAddressCopied,
    WalletDialogTitleTopUp,

    WithdrawTitle,
    WithdrawHintAddress,
    WithdrawHintAmount,
    WithdrawActionMax,
    WithdrawFieldAvailable,
    WithdrawFieldTransactionFee,
    WithdrawFieldTotal,
    WithdrawActionConfirmTransaction,
    WithdrawActionSendTransaction,

    ProfileTitle,
    ProfileTitleLikes,
    ProfileTitleSubscribers,
    ProfileTitleSubscriptions,
    ProfileTitlePublication,

    CommentsTitle,
    CommentsHint,

    ConfirmUnsubscribeDialogMessage,
    ConfirmUnsubscribeDialogActionCancel,
    ConfirmUnsubscribeDialogActionUnsubscribe,

    MyCollectionTitle,
    MyCollectionMessage,
    MyCollectionTitleSlideNft,
    MyCollectionTitleSlideMysteryBox,
    MyCollectionTitleMysteryBox,

    RankSelectionTitle,
    RankSelectionMessage,
    RankSelectionTitleDailyReward,
    RankSelectionTitleDailyUnlock,
    RankSelectionTitleDailyConsumption,

    CreateVideoActionGrantPerms,
    CreateVideoActionFlip,
    CreateVideoActionChoose,

    PreviewVideoActionDiscard,
    PreviewVideoActionProceed,
}