package io.snaps.corecommon.strings

enum class StringKey {

    ActionStart,
    ActionSave,
    ActionReply,
    ActionReload,
    ActionContinue,
    ActionSend,
    ActionConfirm,
    ActionCancel,
    ActionClose,
    ActionDelete,
    ActionHowItWorks,
    ActionOk,

    MessageSuccess,
    MessageCopySuccess,
    MessageConnectionSuccess,
    MessageEmptyVideoFeed,
    MessageNothingFound,
    MessageNoData,
    MessageReferralCodeApplySuccess,

    FieldMinutes,
    FieldMinutesShort,
    FieldSeconds,
    FieldSecondsShort,

    Error,
    ErrorLoadFail,
    ErrorConnection,
    ErrorUnknown,
    ErrorBalanceInSync,
    ErrorRefillGasLimit,
    ErrorCreateVideoLimit,

    OnboardingRankTitle,
    OnboardingRankMessage,
    OnboardingRankAction,
    OnboardingPopularTitle,
    OnboardingPopularMessage,
    OnboardingPopularAction,
    OnboardingTasksTitle,
    OnboardingTasksMessage,
    OnboardingTasksAction,
    OnboardingNftTitle,
    OnboardingNftText,
    OnboardingNftAction,
    OnboardingReferralTitle,
    OnboardingReferralMessage,
    OnboardingReferralAction,
    OnboardingWalletTitle,
    OnboardingWalletText,
    OnboardingWalletAction,
    OnboardingRewardsTitle,
    OnboardingRewardsMessage,
    OnboardingRewardsAction,

    AppUpdateTitle,
    AppUpdateMessage,
    AppUpdateAction,

    BottomBarTitleFeed,
    BottomBarTitleSearch,
    BottomBarTitleTasks,
    BottomBarTitleNft,
    BottomBarTitleReferrals,

    TransactionTitleWithdrawal,
    TransactionTitleSend,
    TransactionTitleNftReward,
    TransactionTitleGlassesMaintaince,
    TransactionTitleGasFee,
    TransactionTitleNone,
    TransactionTitleSubscribersPromo,
    TransactionTitleViewsPromo,
    TransactionTitleMoveToUnlock,
    TransactionTitleReverse,
    TransactionTitleReferralReward,
    TransactionTitleBloggerGlassesLikesPromo,
    TransactionTitleReferralPurchaiseReward,

    RegistrationMessagePrivacyPolicy,
    RegistrationActionPrivacyPolicy,
    RegistrationActionTermsOfUse,
    RegistrationActionLoginWithEmail,
    RegistrationActionLoginWithGoogle,
    RegistrationActionLoginWithFacebook,
    RegistrationActionLoginWithTwitter,
    RegistrationTitle,
    RegistrationFieldOr,
    RegistrationDialogSignInTitle,
    RegistrationDialogSignInMessage,
    RegistrationDialogSignInHintEmail,
    RegistrationDialogSignInHintPassword,
    RegistrationDialogSignInActionLogin,
    RegistrationDialogSignInActionRegistration,
    RegistrationDialogSignInActionForgotPassword,
    RegistrationDialogSignUpTitle,
    RegistrationDialogSignUpMessage,
    RegistrationDialogSignUpHintEmail,
    RegistrationDialogSignUpHintPassword,
    RegistrationDialogSignUpHintConfirmPassword,
    RegistrationDialogSignUpActionLogin,
    RegistrationDialogSignUpActionRegistration,
    RegistrationDialogVerificationTitle,
    RegistrationDialogVerificationMessage,
    RegistrationDialogResetPasswordTitle,
    RegistrationDialogResetPasswordAction,
    RegistrationDialogResetPasswordFieldEnterEmail,
    RegistrationDialogResetPasswordHintEmail,
    RegistrationDialogResetPasswordInstructionsMessage,

    SubsActionSubscriptions,
    SubsActionSubscribers,
    SubsActionFollow,
    SubsActionFollowing,

    CreateUserTitle,
    CreateUserMessage,
    CreateUserHintNickname,
    CreateUserFieldPhotoUploaded,
    CreateUserActionUploadPhoto,
    CreateUserActionStart,

    PhotoDialogTitle,
    PhotoDialogActionPickPhoto,
    PhotoDialogActionTakePhoto,
    PhotoDialogActionCancel,

    SearchHint,
    SearchVideosTitle,
    SearchProfilesTitle,

    WalletImportTitle,
    WalletImportMessageEnterPhrase,
    WalletImportMessagePhraseExplanation,
    WalletImportHint,

    ConnectWalletTitle,
    ConnectWalletMessage,
    ConnectWalletActionCreate,
    ConnectWalletActionImport,

    CreateWalletTitle,
    CreateWalletMessage,
    CreateWalletAction,

    CreatedWalletTitle,
    CreatedWalletMessage,
    CreatedWalletAction,

    MnemonicsTitle,
    MnemonicsMessage,

    WalletSecurityDialogTitle,
    WalletSecurityDialogMessage,
    WalletSecurityDialogMessageScreenLockNotSet,
    WalletSecurityDialogMessageUserNotAuthenticatedRecently,

    VerificationTitle,
    VerificationMessage,

    ReferralProgramTitleSliderMain,
    ReferralProgramTitleSliderMyReferrals,
    ReferralProgramTitleFootnoteMain,
    ReferralProgramTitleFootnoteMyReferrals,
    ReferralProgramTitleEnterCode,
    ReferralProgramMessageEnterCode,
    ReferralProgramActionEnterCode,
    ReferralProgramHintCode,
    ReferralProgramHintLink,
    ReferralProgramTitleDirectReferral,
    ReferralProgramMessageDirectReferral,
    ReferralProgramActionInviteUser,
    ReferralProgramInviteDialogTitle,
    ReferralProgramInviteDialogMessage,
    ReferralProgramDialogActionClose,
    ReferralProgramCodeDialogTitle,
    ReferralProgramCodeDialogMessage,
    ReferralProgramCodeDialogActionInvite,
    ReferralProgramCodeDialogHintEnterCode,
    ReferralProgramMessageReferralCodeCopied,
    ReferralProgramMessageReferralLinkCopied,
    ReferralProgramMessageFootnoteMain,
    ReferralProgramMessageFootnoteMyReferrals,
    ReferralProgramTitleNoReferrals,
    ReferralProgramMessageNoReferrals,
    ReferralProgramActionReferralProgram,
    ReferralProgramDialogTitleFootnoteMain1,
    ReferralProgramDialogTitleFootnoteMain2,
    ReferralProgramDialogMessageFootnoteMain1,
    ReferralProgramDialogMessageFootnoteMain2,
    ReferralProgramDialogActionFootnoteMain2,
    ReferralProgramDialogTitleFootnoteMyReferrals,
    ReferralProgramDialogMessageFootnoteMyReferrals,
    ReferralProgramDialogMessageFootnoteMyReferralsDisclaimer,
    ReferralProgramDialogTitleFootnoteMyReferralsLevel1,
    ReferralProgramDialogMessageFootnoteMyReferralsLevel1,
    ReferralProgramDialogTitleFootnoteMyReferralsLevel2,
    ReferralProgramDialogMessageFootnoteMyReferralsLevel2,
    ReferralProgramDialogTitleFootnoteMyReferralsLevel3,
    ReferralProgramDialogMessageFootnoteMyReferralsLevel3,
    ReferralProgramMessageShare,
    ReferralProgramDialogMessageApplyCode,
    ReferralProgramDialogMessageCodeEntered,

    SettingsTitle,
    SettingsTitleWallet,
    SettingsTitleReferralProgram,
    SettingsTitleSocialNetworks,
    SettingsTitleAboutProject,
    SettingsActionLogout,
    SettingsActionDeleteAccount,
    SettingsDialogLogoutTitle,
    SettingsDialogLogoutMessage,
    SettingsDialogDeleteAccountTitle,

    SocialNetworksTitle,
    SocialNetworksTitleDiscord,
    SocialNetworksTitleTelegram,

    TasksTitleSlideCurrent,
    TasksTitleSlideHistory,
    TasksTitleFootnoteCurrent,
    TasksTitleFootnoteHistory,
    TasksMessageFootnoteCurrent,
    TasksMessageFootnoteHistory,
    TasksTitleRemainingTime,
    TaskFieldJobCompleted,
    TasksMessageTaskCounted,
    TasksMessageTaskInProgress,
    TasksTitleWatchVideo,
    TasksMessageWatchVideo,
    TasksTitleLike,
    TasksMessageLike,
    TasksTitlePublishVideo,
    TasksMessagePublishVideo,
    TasksTitleSubscribe,
    TasksMessageSubscribe,
    TasksTitleSocialPost,
    TasksMessageSocialPost,
    TasksMessageSocialPostNotPosted,
    TasksMessageSocialPostNotSendToVerify,
    TasksMessageSocialPostReview,
    TasksMessageSocialPostRejected,
    TasksErrorRepairGlasses,
    TasksDialogTitleFootnote1,
    TasksDialogMessageFootnote1,
    TasksDialogTitleFootnote2,
    TasksDialogMessageFootnote2,
    TasksDialogTitleFootnote3,
    TasksDialogMessageFootnote3,

    TaskWatchVideoTitle,
    TaskWatchVideoMessage,

    TaskLikeTitle,
    TaskLikeMessage,

    TaskSubscribeTitle,
    TaskSubscribeMessage,

    TaskPublishVideoTitle,
    TaskPublishVideoMessage,

    TaskSocialPostTitle,
    TaskSocialPostMessage,

    TaskSocialShareTitle,
    TaskSocialShareMessage,

    TaskShareTitle,
    TaskShareTitleConnectInstagram,
    TaskShareActionConnect,
    TaskShareActionSavePhoto,
    TaskShareActionPostToInstagram,
    TaskShareMessagePhotoSaved,
    TaskShareFieldDownloadApp,
    TaskShareFieldEarnCryptocurrencies,
    TaskShareMessagePostInstagram,
    TaskShareTitleShareImage,
    TaskShareErrorNoInstagramConnected,
    TaskShareMessageShareImageWrite,
    TaskShareMessageShareImageMe,
    TaskShareMessageShareImageAndWillTell,
    TaskShareMessageShareImageEarned,
    TaskShareFieldShareImageCurrency,
    TaskShareErrorPostToInstagramLimit,
    TaskShareDialogTitle,
    TaskShareDialogMessageRequirement1,
    TaskShareDialogMessageRequirement2,
    TaskShareDialogMessageRequirement3,
    TaskShareDialogMessageRequirement4,
    TaskShareDialogMessageRequirement5,
    TaskShareDialogMessageRequirement6,
    TaskShareDialogMessageRequirement7,

    TaskFindPointsTitle,
    TaskFindPointsTitleConnectInstagram,
    TaskFindPointsTitlePointId,
    TaskFindPointsMessage,
    TaskFindPointsActionConnect,
    TaskFindPointsActionVerify,
    TaskFindPointsActionNotFound,
    TaskFindPointsTitleSponsor,

    WalletSettingsTitle,
    WalletSettingsTitleBackup,
    WalletSettingsMessageBackup,
    WalletSettingsBackupDialogTitle,
    WalletSettingsBackupDialogMessage,
    WalletSettingsBackupDialogAction,

    BackupWalletKeyTitle,
    BackupWalletKeyMessage,
    BackupWalletKeyActionHold,

    WalletTitle,
    WalletTitlePaymentStatus,
    WalletFieldPaymentStatusInProcess,
    WalletFieldPaymentStatusRejected,
    WalletTitlePaymentTransactionId,
    WalletMessagePaymentRejected,
    WalletActionPaymentRejected,
    WalletActionTopUp,
    WalletActionWithdraw,
    WalletActionExchange,
    WalletTitleBalance,
    WalletTitleSelectCurrency,
    WalletTitleName,
    WalletTitleQuantity,
    WalletTitleDateTransfer,
    WalletTitleTransactionsEmpty,
    WalletFieldTotal,
    WalletMessageTopUp,
    WalletMessageAddressCopied,
    WalletMessageTransactionsEmpty,
    WalletDialogTitleTopUp,
    WalletDialogSellSnapsMessage,

    RewardsTitle,
    RewardsTitleFootnote,
    RewardsTitleAvailableRewards,
    RewardsTitleLockedRewards,
    RewardsTitleHistory,
    RewardsMessageFootnote,
    RewardsMessageAvailableRewards,
    RewardsMessageLockedRewards,
    RewardsActionClaim,
    RewardsErrorInsufficientBalance,
    RewardsErrorRepairGlasses,
    RewardsFieldFilterLocked,
    RewardsFieldFilterUnlocked,
    RewardsDialogTitleFootnote1,
    RewardsDialogTitleFootnote2,
    RewardsDialogMessageFootnote1,
    RewardsDialogMessageFootnote2,
    RewardsDialogTitleClaim,
    RewardsDialogActionClaim,
    RewardsDialogHintClaim,
    RewardsDialogActionMax,
    RewardsDialogFieldAvailable,
    RewardsDialogRepairNftTitle,
    RewardsDialogRepairNftText,
    RewardsDialogRepairNftAction,

    WithdrawTitle,
    WithdrawHintAddress,
    WithdrawHintAmount,
    WithdrawActionMax,
    WithdrawFieldAvailable,
    WithdrawFieldTransactionFee,
    WithdrawFieldTotal,
    WithdrawActionConfirmTransaction,
    WithdrawActionSendTransaction,
    WithdrawErrorInvalidAddress,
    WithdrawErrorInvalidAmount,
    WithdrawDialogWithdrawTitle,
    WithdrawDialogWithdrawSuccessTitle,
    WithdrawDialogWithdrawSuccessMessage,
    WithdrawDialogWithdrawSuccessAction,

    WithdrawSnapsTitle,
    WithdrawSnapsMessageAssurance,
    WithdrawSnapsHintAmount,
    WithdrawSnapsActionMax,
    WithdrawSnapsHintCardNumber,
    WithdrawSnapsHintRepeatCardNumber,
    WithdrawSnapsTitleBalance,
    WithdrawSnapsTitleComission,
    WithdrawSnapsTitleTotal,

    ExchangeTitle,

    ProfileTitle,
    ProfileTitleLikes,
    ProfileTitleSubscribers,
    ProfileTitleSubscriptions,
    ProfileTitlePublication,
    ProfileMessageEmptyVideos,
    ProfileTitleLiked,
    ProfileTitleShorts,

    EditProfileTitle,
    EditProfileFieldPhoto,
    EditProfileHintName,

    EditNameTitle,
    EditNameAction,
    EditNameMessage,

    CommentsTitle,
    CommentsHint,

    ConfirmUnsubscribeDialogMessage,
    ConfirmUnsubscribeDialogActionCancel,
    ConfirmUnsubscribeDialogActionUnsubscribe,

    MyCollectionTitle,
    MyCollectionMessage,
    MyCollectionTitleSlideNft,
    MyCollectionTitleSlideMysteryBox,
    MyCollectionTitleMysteryBox,
    MyCollectionFieldNeedToRepair,
    MyCollectionActionRepairGlasses,
    MyCollectionActionProcessing,
    MyCollectionFieldBonus,
    MyCollectionFieldExperience,
    MyCollectionFieldLevel,
    MyCollectionFieldUpperThreshold,
    MyCollectionErrorNoEnoughSnp,
    MyCollectionDialogRepairSuccessTitle,
    MyCollectionDialogRepairSuccessAction,
    MyCollectionDialogWithBnbSuccessTitle,
    MyCollectionDialogWithBnbSuccessMessage,
    MyCollectionDialogWithBnbSuccessAction,

    DialogLimitedGasTitle,
    DialogLimitedGasMessage,
    DialogLimitedGasAction,

    DialogSummaryTitle,
    DialogSummaryTitleFrom,
    DialogSummaryTitleTo,
    DialogSummaryTitleGasPrice,
    DialogSummaryTitleTotal,

    RankSelectionTitle,
    RankSelectionActionFootnote,
    RankSelectionTitleDailyReward,
    RankSelectionTitleDailyUnlock,
    RankSelectionTitleDailyConsumption,
    RankSelectionMessageNotAvailable,
    RankSelectionDialogTitleFootnote1,
    RankSelectionDialogMessageFootnote1,
    RankSelectionDialogActionFootnote1,

    CreateVideoActionGrantPerms,
    CreateVideoActionFlip,
    CreateVideoActionChoose,
    CreateVideoMessageDurationLimit,

    PreviewVideoActionDiscard,
    PreviewVideoActionProceed,
    PreviewVideoMessageSuccess,

    UploadVideoTitle,
    UploadVideoTitlePreview,
    UploadVideoHintTitle,
    UploadVideoHintDescription,
    UploadVideoActionPublish,

    PurchaseTitle,
    PurchaseTitlePrice,
    PurchaseTitleNotAvailable,
    PurchaseTitleRank,
    PurchaseFieldLevel,
    PurchaseFieldCostFree,
    PurchaseTitleDailyReward,
    PurchaseMessageDailyReward1,
    PurchaseMessageDailyReward2,
    PurchaseTitleDailyUnlock,
    PurchaseMessageDailyUnlock1,
    PurchaseMessageDailyUnlock2,
    PurchaseTitleDailyCosts,
    PurchaseMessageDailyCosts,
    PurchaseActionBuyInStore,
    PurchaseActionBuyWithBNB,
    PurchaseActionFree,
    PurchaseFieldOff,
    PurchaseMessageSuccess,
    PurchaseDialogWithBnbTitle,
    PurchaseErrorNotEnoughBnb,

    VideoClipActionDelete,
    VideoClipTitleAction,
    VideoClipDialogConfirmDeleteMessage,

    NftDetailsMessageDailyReward,
    NftDetailsTitleEarnings,
    NftDetailsMessageEarnings,
    NftDetailsTitleCondition,
    NftDetailsMessageCondition,
    NftDetailsTitleLevel,
    NftDetailsMessageLevel,
    NftDetailsFieldLeftCopies,
    NftDetailsTitleLiker,
    NftDetailsMessageLiker,

    MainVideoFeedTitleForYou,
    MainVideoFeedTitleSubscriptions,

    AboutProjectTitlePrivacyPolicy,
    AboutProjectTitleTermsOfUse,
    AboutProjectTitleWhitepaper,
}