package io.snaps.corecommon.strings

enum class StringKey {

    ActionStart,
    ActionSave,
    ActionReply,
    ActionReload,
    ActionContinue,
    ActionSend,
    ActionConfirm,
    ActionCancel,
    ActionClose,
    ActionDelete,
    ActionHowItWorks,
    ActionOk,

    MessageConnectionSuccess,

    Error,
    ErrorLoadFail,
    ErrorConnection,
    ErrorUnknown,

    MessageEmptyVideoFeed,
    MessageNothingFound,

    OnboardingRankTitle,
    OnboardingRankText,
    OnboardingRankAction,
    OnboardingPopularTitle,
    OnboardingPopularText,
    OnboardingPopularAction,
    OnboardingTasksTitle,
    OnboardingTasksText,
    OnboardingTasksAction,
    OnboardingNftTitle,
    OnboardingNftText,
    OnboardingNftAction,
    OnboardingReferralTitle,
    OnboardingReferralText,
    OnboardingReferralAction,
    OnboardingWalletTitle,
    OnboardingWalletText,
    OnboardingWalletAction,
    OnboardingRewardsTitle,
    OnboardingRewardsText,
    OnboardingRewardsAction,

    BottomBarTitleFeed,
    BottomBarTitleSearch,
    BottomBarTitleTasks,
    BottomBarTitleNft,
    BottomBarTitleReferrals,

    RegistrationMessagePrivacyPolicy,
    RegistrationActionPrivacyPolicy,
    RegistrationActionTermsOfUse,
    RegistrationActionLoginWithEmail,
    RegistrationActionLoginWithGoogle,
    RegistrationActionLoginWithFacebook,
    RegistrationActionLoginWithTwitter,
    RegistrationTitle,
    RegistrationFieldOr,
    RegistrationDialogSignInTitle,
    RegistrationDialogSignInMessage,
    RegistrationDialogSignInHintEmail,
    RegistrationDialogSignInHintPassword,
    RegistrationDialogSignInActionLogin,
    RegistrationDialogSignInActionRegistration,
    RegistrationDialogSignInActionForgotPassword,
    RegistrationDialogSignUpTitle,
    RegistrationDialogSignUpMessage,
    RegistrationDialogSignUpHintEmail,
    RegistrationDialogSignUpHintPassword,
    RegistrationDialogSignUpHintConfirmPassword,
    RegistrationDialogSignUpActionLogin,
    RegistrationDialogSignUpActionRegistration,
    RegistrationDialogVerificationTitle,
    RegistrationDialogVerificationMessage,
    RegistrationDialogResetPasswordTitle,
    RegistrationDialogResetPasswordAction,
    RegistrationDialogResetPasswordFieldEnterEmail,
    RegistrationDialogResetPasswordHintEmail,
    RegistrationDialogResetPasswordInstructionsMessage,

    SubsActionSubscriptions,
    SubsActionSubscribers,
    SubsActionFollow,
    SubsActionFollowing,

    CreateUserTitle,
    CreateUserMessage,
    CreateUserHintNickname,
    CreateUserFieldPhotoUploaded,
    CreateUserActionUploadPhoto,
    CreateUserActionStart,

    PhotoDialogTitle,
    PhotoDialogActionPickPhoto,
    PhotoDialogActionTakePhoto,
    PhotoDialogActionCancel,

    SearchHint,
    SearchVideosTitle,
    SearchProfilesTitle,

    WalletImportTitle,
    WalletImportMessageEnterPhrase,
    WalletImportMessagePhraseExplanation,
    WalletImportHint,

    ConnectWalletTitle,
    ConnectWalletMessage,
    ConnectWalletActionCreate,
    ConnectWalletActionImport,

    CreateWalletTitle,
    CreateWalletMessage,
    CreateWalletAction,

    CreatedWalletTitle,
    CreatedWalletMessage,
    CreatedWalletAction,

    MnemonicsTitle,
    MnemonicsMessage,

    DeviceNotSecuredDialogTitle,
    DeviceNotSecuredDialogMessage,

    VerificationTitle,
    VerificationMessage,

    ReferralProgramTitleSliderMain,
    ReferralProgramTitleSliderMyReferrals,
    ReferralProgramTitleFootnoteMain,
    ReferralProgramTitleFootnoteMyReferrals,
    ReferralProgramTitleEnterCode,
    ReferralProgramMessageEnterCode,
    ReferralProgramActionEnterCode,
    ReferralProgramHintCode,
    ReferralProgramHintLink,
    ReferralProgramTitleDirectReferral,
    ReferralProgramMessageDirectReferral,
    ReferralProgramActionInviteUser,
    ReferralProgramInviteDialogTitle,
    ReferralProgramInviteDialogMessage,
    ReferralProgramDialogActionClose,
    ReferralProgramCodeDialogTitle,
    ReferralProgramCodeDialogMessage,
    ReferralProgramCodeDialogActionInvite,
    ReferralProgramCodeDialogHintEnterCode,
    ReferralProgramMessageReferralCodeCopied,
    ReferralProgramMessageReferralLinkCopied,
    ReferralProgramMessageFootnoteMain,
    ReferralProgramMessageFootnoteMyReferrals,
    ReferralProgramTitleNoReferrals,
    ReferralProgramMessageNoReferrals,
    ReferralProgramDialogTitleFootnoteMain1,
    ReferralProgramDialogTitleFootnoteMain2,
    ReferralProgramDialogMessageFootnoteMain1,
    ReferralProgramDialogMessageFootnoteMain2,
    ReferralProgramDialogActionFootnoteMain2,
    ReferralProgramDialogTitleFootnoteMyReferrals,
    ReferralProgramDialogMessageFootnoteMyReferrals,
    ReferralProgramDialogMessageFootnoteMyReferralsDisclaimer,
    ReferralProgramDialogTitleFootnoteMyReferralsLevel1,
    ReferralProgramDialogMessageFootnoteMyReferralsLevel1,
    ReferralProgramDialogTitleFootnoteMyReferralsLevel2,
    ReferralProgramDialogMessageFootnoteMyReferralsLevel2,
    ReferralProgramDialogTitleFootnoteMyReferralsLevel3,
    ReferralProgramDialogMessageFootnoteMyReferralsLevel3,

    SettingsTitle,
    SettingsTitleWallet,
    SettingsTitleReferralProgram,
    SettingsTitleSocialNetworks,
    SettingsTitleAboutProject,
    SettingsActionLogout,
    SettingsActionDeleteAccount,

    SocialNetworksTitle,
    SocialNetworksTitleDiscord,
    SocialNetworksTitleTelegram,

    TasksTitleSlideCurrent,
    TasksTitleSlideHistory,
    TasksTitleFootnoteCurrent,
    TasksTitleFootnoteHistory,
    TasksMessageFootnoteCurrent,
    TasksMessageFootnoteHistory,
    TasksTitleRemainingTime,
    TaskFieldJobCompleted,
    TasksMessageTaskCounted,
    TasksMessageTaskInProgress,
    TasksTitleWatchVideo,
    TasksDescriptionWatchVideo,
    TasksTitleLike,
    TasksDescriptionLike,
    TasksTitlePublishVideo,
    TasksDescriptionPublishVideo,
    TasksTitleSubscribe,
    TasksDescriptionSubscribe,
    TasksTitleSocialPost,
    TasksDescriptionSocialPost,
    TasksFieldSocialPostNotPosted,
    TasksFieldSocialPostNotSendToVerify,
    TasksFieldSocialPostWaitForVerification,
    TasksFieldSocialPostRejected,
    TasksDialogTitleFootnote1,
    TasksDialogMessageFootnote1,
    TasksDialogTitleFootnote2,
    TasksDialogMessageFootnote2,
    TasksDialogTitleFootnote3,
    TasksDialogMessageFootnote3,

    TaskWatchVideoTitle,
    TaskWatchVideoDescription,

    TaskLikeTitle,
    TaskLikeDescription,

    TaskSubscribeTitle,
    TaskSubscribeDescription,

    TaskPublishVideoTitle,
    TaskPublishVideoDescription,

    TaskSocialPostTitle,
    TaskSocialPostDescription,

    TaskSocialShareTitle,
    TaskSocialShareDescription,

    TaskShareTitle,
    TaskShareTitleConnectInstagram,
    TaskShareActionConnect,
    TaskShareActionSavePhoto,
    TaskShareActionPostToInstagram,
    TaskShareMessagePhotoSaved,
    TaskShareFieldDownloadApp,
    TaskShareFieldEarnCryptocurrencies,
    TaskShareMessagePostInstagram,

    TaskFindPointsTitle,
    TaskFindPointsTitleConnectInstagram,
    TaskFindPointsTitlePointId,
    TaskFindPointsMessage,
    TaskFindPointsActionConnect,
    TaskFindPointsActionVerify,
    TaskFindPointsActionNotFound,
    TaskFindPointsTitleSponsor,

    WalletSettingsTitle,
    WalletSettingsTitleBackup,
    WalletSettingsDescriptionBackup,
    WalletSettingsBackupDialogTitle,
    WalletSettingsBackupDialogMessage,
    WalletSettingsBackupDialogAction,

    BackupWalletKeyTitle,
    BackupWalletKeyMessage,
    BackupWalletKeyActionHold,

    WalletTitle,
    WalletActionTopUp,
    WalletActionWithdraw,
    WalletActionExchange,
    WalletTitleBalance,
    WalletTitleSelectCurrency,
    WalletTitleName,
    WalletTitleQuantity,
    WalletTitleDateTransfer,
    WalletTitleTransactionsEmpty,
    WalletFieldTotal,
    WalletMessageTopUp,
    WalletMessageAddressCopied,
    WalletMessageTransactionsEmpty,
    WalletDialogTitleTopUp,

    RewardsTitle,
    RewardsTitleFootnote,
    RewardsTitleAvailableRewards,
    RewardsTitleLockedRewards,
    RewardsTitleHistory,
    RewardsMessageFootnote,
    RewardsMessageAvailableRewards,
    RewardsMessageLockedRewards,
    RewardsActionClaim,
    RewardsErrorInsufficientBalance,
    RewardsErrorRepairGlasses,
    RewardsDialogTitleFootnote1,
    RewardsDialogTitleFootnote2,
    RewardsDialogMessageFootnote1,
    RewardsDialogMessageFootnote2,
    RewardsDialogTitleClaim,
    RewardsDialogActionClaim,
    RewardsDialogHintClaim,
    RewardsDialogActionMax,
    RewardsDialogFieldAvailable,

    WithdrawTitle,
    WithdrawHintAddress,
    WithdrawHintAmount,
    WithdrawActionMax,
    WithdrawFieldAvailable,
    WithdrawFieldTransactionFee,
    WithdrawFieldTotal,
    WithdrawActionConfirmTransaction,
    WithdrawActionSendTransaction,

    ExchangeTitle,

    ProfileTitle,
    ProfileTitleLikes,
    ProfileTitleSubscribers,
    ProfileTitleSubscriptions,
    ProfileTitlePublication,

    CommentsTitle,
    CommentsHint,

    ConfirmUnsubscribeDialogMessage,
    ConfirmUnsubscribeDialogActionCancel,
    ConfirmUnsubscribeDialogActionUnsubscribe,

    MyCollectionTitle,
    MyCollectionMessage,
    MyCollectionTitleSlideNft,
    MyCollectionTitleSlideMysteryBox,
    MyCollectionTitleMysteryBox,
    MyCollectionFieldNeedToRepair,
    MyCollectionActionRepairGlasses,
    MyCollectionActionProcessing,
    MyCollectionFieldBonus,
    MyCollectionFieldExperience,
    MyCollectionFieldLevel,
    MyCollectionFieldUpperThreshold,

    RankSelectionTitle,
    RankSelectionActionFootnote,
    RankSelectionTitleDailyReward,
    RankSelectionTitleDailyUnlock,
    RankSelectionTitleDailyConsumption,
    RankSelectionMessageNotAvailable,
    RankSelectionDialogTitleFootnote1,
    RankSelectionDialogMessageFootnote1,
    RankSelectionDialogActionFootnote1,

    CreateVideoActionGrantPerms,
    CreateVideoActionFlip,
    CreateVideoActionChoose,
    CreateVideoMessageDurationLimit,

    PreviewVideoActionDiscard,
    PreviewVideoActionProceed,
    PreviewVideoMessageSuccess,

    UploadVideoTitle,
    UploadVideoHintTitle,
    UploadVideoHintDescription,
    UploadVideoActionPublish,

    PurchaseTitle,
    PurchaseTitlePrice,
    PurchaseTitleNotAvailable,
    PurchaseTitleRank,
    PurchaseFieldLevel,
    PurchaseTitleDailyReward,
    PurchaseDescriptionDailyReward,
    PurchaseMessageDailyReward,
    PurchaseTitleDailyUnlock,
    PurchaseDescriptionDailyUnlock,
    PurchaseMessageDailyUnlock,
    PurchaseTitleDailyCosts,
    PurchaseDescriptionDailyCosts,
    PurchaseActionBuyInStore,
    PurchaseActionBuyWithBNB,
    PurchaseActionFree,
    PurchaseFieldOff,

    VideoClipActionDelete,
    VideoClipTitleAction,
    VideoClipDialogConfirmDeleteMessage,

    NftDetailsDescriptionDailyReward,
    NftDetailsTitleEarnings,
    NftDetailsDescriptionEarnings,
    NftDetailsTitleCondition,
    NftDetailsDescriptionCondition,
    NftDetailsTitleLevel,
    NftDetailsDescriptionLevel,

    MainVideoFeedTitleForYou,
    MainVideoFeedTitleSubscriptions,
}